[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build", "cp -r .next/static .next/standalone/.next/static", "cp -r public .next/standalone/public || true"]

[start]
cmd = "sh -c 'npx prisma migrate deploy; HOSTNAME=0.0.0.0 node .next/standalone/server.js'"
