[build]
builder = "nixpacks"

[deploy]
startCommand = "(npx prisma migrate deploy || echo 'Migration skipped') && HOSTNAME=0.0.0.0 node .next/standalone/server.js"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
